dependencies:
  - name: mongodb
    version: 7.14.1
    repository: https://charts.bitnami.com/bitnami/
    condition: mongodb.enabled
  - name: postgresql
    version: 8.1.4
    repository: https://charts.helm.sh/stable/
    condition: postgresql.enabled