{{- if .Values.hydra.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "reactioncommerce.fullname" . }}-hydra
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: hydra
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- if .Values.hydra.service.annotations }}
{{ toYaml .Values.hydra.service.annotations | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.hydra.service.type }}
  selector:
    app: {{ template "reactioncommerce.name" . }}
    component: hydra
    release: {{ .Release.Name }}
  ports:
    - name: "hydra"
      port: 4444
      targetPort: 4444
    - name: "admin"
      port: 4445
      targetPort: 4445
    - name: "tokens"
      port: 5555
      targetPort: 5555
{{- end }}