{{- if .Values.identity.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: identity
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-identity
  namespace: {{ .Release.Namespace | quote }} 
spec:
  selector:
    matchLabels:
      app: {{ template "reactioncommerce.name" . }}
      component: identity
      release: {{ .Release.Name }}
  replicas: {{ .Values.identity.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "reactioncommerce.name" . }}
        component: identity
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.identity.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.identity.image.imagePullSecret }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-identity
        image: "{{ .Values.identity.image.repository }}:{{ .Values.identity.image.tag }}"
        imagePullPolicy: {{ .Values.identity.image.pullPolicy }}
        ports:
          - name: identity
            containerPort: 4100
            protocol: TCP
        envFrom:
          - secretRef:
              name: {{ template "reactioncommerce.fullname" . }}
          - configMapRef:
              name: {{ template "reactioncommerce.fullname" . }}-identity
{{- end }}
