{{- if .Values.identity.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: identity
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "reactioncommerce.fullname" . }}-identity
  namespace: {{ .Release.Namespace | quote }} 
data:
  ## Force UTC timezone
  TZ: "Etc/UTC"
  NODE_ENV: "production"
  API_URL: {{ printf "%s/graphql" .Values.api.rootUrl | quote }}
  HYDRA_ADMIN_URL: {{ printf "http://%s-hydra.%s.svc:4445" ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  HYDRA_TOKEN_URL: {{ printf "http://%s-hydra.%s.svc:4444/oauth2/token" ( include "reactioncommerce.fullname" . ) .Release.Namespace | quote }}
  OAUTH2_CLIENT_DOMAINS: {{ include "reactioncommerce.web.url" . | quote }}
  PORT: "4100"
  ROOT_URL: {{ include "reactioncommerce.identity.url" . | quote }}
{{- end }}
