{{- if .Values.kinetic.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "opencommerce.fullname" . }}-kinetic
  labels:
    app: {{ template "opencommerce.name" . }}
    component: kinetic
    chart: {{ template "opencommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- if .Values.kinetic.service.annotations }}
{{ toYaml .Values.kinetic.service.annotations | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kinetic.service.type }}
  selector:
    app: {{ template "opencommerce.name" . }}
    component: kinetic
    release: {{ .Release.Name }}
  ports:
    - name: "kinetic"
      port: 3001
      targetPort: 3001
{{- end }}
