{{- if .Values.kinetic.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "opencommerce.name" . }}
    component: kinetic
    chart: {{ template "opencommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "opencommerce.fullname" . }}-kinetic
  namespace: {{ .Release.Namespace | quote }} 
data:
  ## Force UTC timezone
  TZ: "Etc/UTC"
  NODE_ENV: "production"
  VITE_API_URL:  {{ printf "%s/graphql" ( include "opencommerce.api.url" . ) | quote }}
{{- end }}
